[build-system]
requires = ["setuptools>=67.7"]
build-backend = "setuptools.build_meta"

[project]
name = "redis-rqueue"
version = "1.0.0"
requires-python = ">=3.8"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
